# Generated by Django 5.2.7 on 2026-03-27 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonationCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('contact', models.CharField(max_length=15)),
                ('timings', models.CharField(max_length=100)),
                ('categories', models.CharField(max_length=200)),
                ('donation_type', models.CharField(max_length=50)),
                ('guidelines', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
